#!/usr/bin/env bash

#######################################################################
#                            BEGIN CONFIG                             #
#######################################################################

# Use a custom lock script
#LOCKSCRIPT="i3lock-extra -m pixelize"

# Colors: FG (foreground), BG (background), HL (highlighted)
FG_COLOR="#bbbbbb"
BG_COLOR="#111111"
HLFG_COLOR="#111111"
HLBG_COLOR="#bbbbbb"
BORDER_COLOR="#222222"

# Options not related to colors
#WOFI_TEXT=":"
#WOFI_OPTIONS=(-width -11 -location 0 -hide-scrollbar -bw 30 -color-window "#dd310027,#dd0310027,#dd310027" -padding 5)
#WOFI_OPTIONS=(-width -18 -location 4 -hide-scrollbar -color-window "#cc310027,#00a0009a,#cc310027" -padding 5 -font "Sourcecode Pro Regular 10, FontAwesome 9")
WOFI_OPTIONS=(-theme ~/.config/wofi/power-pwofiles.rasi)

#######################################################################
#                             END CONFIG                              #
#######################################################################

# Check whether the user-defined launcher is valid
launcher_list=(wofi zenity)

typeset -A menu
# The menu that will be displayed
menu=(
	[US Qwerty]="setxkbmap -layout us"
	[US Dvorak]="setxkbmap -layout us -variant dvorak"
	[KH Khmer]="setxkbmap -layout kh"
)

menu_nrows=${#menu[@]}

# Menu entries that may trigger a confirmation message
menu_confirm="Shutdown Reboot Hibernate Suspend Halt Logout"

wofi_colors=(-bc "${BORDER_COLOR}" -bg "${BG_COLOR}" -fg "${FG_COLOR}"
	-hlfg "${HLFG_COLOR}" -hlbg "${HLBG_COLOR}")
launcher_exe="wofi"
launcher_options=(-dmenu -i -lines "${menu_nrows}" -p "${WOFI_TEXT}"
	"${wofi_colors}" "${WOFI_OPTIONS[@]}")

# No launcher available
if [[ -z "${launcher_exe}" ]]; then
	exit 1
fi

launcher=(${launcher_exe} "${launcher_options[@]}")
# this code is executed and the result is stored in $selection
selection="$(printf '%s\n' "${!menu[@]}" | sort | "${launcher[@]}")"

notify-send "Profile" "${selection}"
notify-send "Profile" "${menu[${selection}]}"
# execute the commands for hyprland

${menu[${selection}]}
pkill -RTMIN+10 -x waybar
